spring:
  datasource:
    url: ${{ secrets.ORACLE_URL }}
    username: ${{ secrets.ORACLE_USERNAME }}
    password: ${{ secrets.ORACLE_PASSWORD }}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

